remote_theme: chrisrhymes/bulma-clean-theme

#baseurl: '/'

title: 'Spell Revisions'
version: 'v4b18'
bg2ee_version: 'v2.5.16.6'

collections_dir: collections
collections:
  spells:
    output: true
    permalink: /:collection/:path
  vanilla-spells:
    output: true
    permalink: /:collection/:path

defaults:
  -
    scope:
      path: ""
      type: "spells"
    values:
      layout: "spell-modded"
  -
    scope:
      path: ""
      type: "vanilla-spells"
    values:
      layout: "spell-vanilla"
